### PR TITLE
Feature: course worker node endpoint

### LINKED ISSUE #56: Course Worker Nodes Endpoint
Define new client endpoint `GET /api/v1/worker/[course_id]/all` which shows the worker nodes for a specific course. Currently, all worked nodes are available to all courses but later we can have a quota or some policy as to how much of the grading cluster a course has access to.

This should return:
```
{
     "worker_nodes": [
             {
                  "hostname": <hostname of the machine on which the grader is running>,
                  "jobs_processed": <number of jobs processed since joining the cluster>,
                  "busy": <True/False>,
                  "alive": <True/False>
             }, ...
       ]
}
```

### PR DESCRIPTION
**Pull request by ayushr2**
Resolves #56 

Also renamed the worker register endpoint to POST `/api/v1/worker` for consistency.

### CODE REVIEW

**Comment by ayushr2** [comment]
A few things to reviewers:
- Fixed a small typo in worker handler which preventing the worker node from being updated correctly in the DB.
- Separated job logs test into its own small test. Do not want to mix testing that with the other integration tests which have their own consistent testing. Before it was added to only one of the integration tests which made it kind of inconsistent.

**Comment by nmagerko** [comment]
Please make separate PRs for separate logical changes if you can. Modifying job logs in a PR about the worker nodes is a bit confusing.

**Comment by nmagerko** [comment]
I'm curious about this `scope` parameter. What would this parameter be used for in the future?

**Comment by ayushr2** [comment]
> I'm curious about this `scope` parameter. What would this parameter be used for in the future?

It can be used for filters like:
- `busy` - return only nodes which are busy
- `available` - return only nodes which are free

Can be removed if it is redundant.

**Comment by nmagerko** [comment]
Oh, I see. I thought it was a query parameter, not a URL parameter. LGTM (although I would suggest throwing a `404` instead of a `501` if the scope is invalid -- 5xx implies it's the server's fault, which I would argue it isn't).

**Comment by ayushr2** [comment]
Fixed!

**Pull request merged**
