### PR TITLE
Fix Ping Endpoint for websockets

### PR DESCRIPTION
**Pull request by ayushr2**
The worker nodes are going to send us pings and that will act as a heartbeat. Earlier we incorrectly had a `on_pong` handler. Changed that to `on_ping`.

### CODE REVIEW

**Comment by rod-lin** [comment]
oh actually it was supposed to be `on_pong` since what i tried to do is to send pings actively from API and the client-side websocket library will automatically respond pong back to the server.

But seems like the pong was not sent back when we are running a job and API ended up kicking the node when they are grading :-(

**Comment by rod-lin** [comment]
I found the problem. Chainlink is doing a non-async process to pull images, which presumably blocked the websocket library's coroutine to respond pings

**Comment by ayushr2** [comment]
> oh actually it was supposed to be on_pong since what i tried to do is to send pings actively from API and the client-side websocket library will automatically respond pong back to the server.

Umm, I think the standard is that the client sends heartbeats (pings) and the server would ack it (pongs).

**Comment by rod-lin** [comment]
hmm ok..

However one tiny caveat is that the client and the server have to agree on the same heartbeat interval. the other way around wouldn't have this problem

**Comment by ayushr2** [comment]
Also, this would add consistency as the HTTP workers use the heartbeat protocol while as you said the ws workers were supposed to work based on the ping-ack protocol (where their liveness is noted on acks or pongs).

Another thing to note is that the websockets library has a default interval of 20 seconds (which is also the deadline after which Broadway declares something dead). We need to reduce that interval to something like 10 seconds (done in illinois-cs241/broadway-grader#33).

**Comment by rod-lin** [comment]
oh wait no i remember now: it was 20s because API sends a ping every 10 seconds, so there could be the case where a worker joined right after a 10s period but missed the ping; and the next time when API pings, the additional network delay might also make API misclassify the node as dead

**Comment by rod-lin** [comment]
tested on grading machines. this https://github.com/illinois-cs241/chainlink/pull/27 should fix this problem

**Comment by ayushr2** [comment]
> API sends a ping every 10 seconds

Where is this configured? The API just accepts connections but does not set any such flag. When the grader establishes the connection (as in illinois-cs241/broadway-grader#33), it sets the interval to be 10 seconds and timeout is defaulted to 20 seconds. And then I guess both server and client follow that configuration.

> So the timeout should be > 10 seconds but idk how much longer

Yes, as mentioned above, the timeout defaults to 20 seconds. It is the interval we need to manually reduce which the other PR does.

> this illinois-cs241/chainlink#27 should fix the problem

Yes, that would allow things to work but the API is not pinging every 10 seconds afaik so there will be some false detections.

**Comment by ayushr2** [comment]
This is where the ping interval and timeout are set: https://github.com/aaugustin/websockets/blob/master/src/websockets/client.py#L377-L378.

**Comment by rod-lin** [comment]
I wasn't aware that `websockets` sends pings periodically.
This is the line in `broadway_api` that currently sends ping actively every heartbeat interval: https://github.com/illinois-cs241/broadway-api/blob/master/broadway_api/callbacks/worker.py#L37

**Comment by rod-lin** [comment]
but yeah I guess it makes more sense to let workers ping servers. I'll make a PR to fix that

**Pull request merged**
